the,article,adverb
and,conjunction
have,verb
i,noun,pronoun
i,noun,pronoun
am,verb
been,verb
away,adjective,adverb
if,noun,conjunction
this,pronoun,article
is,verb
last,adverb,adjective,verb,noun
test,noun,verb,adjective
case,noun,verb,adjective
that,article,conjunction,pronoun,adverb
doing,noun,verb,interjection
today,noun,adverb
a,article,pronoun,preposition,noun,verb
normal,adjective,noun
sentence,verb,noun
of,verb,preposition
some,pronoun,adverb
type,noun,verb
or,conjunction,adjective,noun,adverb,preposition
description,nounwho,pronoun
lives,verb,noun
in,preposition,noun,adjective,adverb
pineapple,noun
under,preposition,adverb
sea,noun
ate,verb
ham,noun,verb
sandwich,noun,verb,adjective
now,adjective,conjunction,noun,adverb
you,pronoun
can,verb,noun
connect,verb
your,pronoun
smartphone,noun
to,adverb,preposition
computer,noun
should,verb
kill,noun,verb
yourself,pronoun,noun
right,adjective,verb,noun,adverbeating,verb,adjective,noun
